####Refer https://github.com/kubernetes/dashboard/wiki/Creating-sample-user
##https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/ for dashborad
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-ram
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: user-ram
    namespace: kube-system